[package]
name = "srs2dge-gizmos"
version = "0.4.0"
edition = "2021"
description = "Simple Rust 2D Game Engine"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srs2dge-core = { path = "../srs2dge-core", version = "0.4" }
srs2dge-presets = { path = "../srs2dge-presets", version = "0.4" }
srs2dge-text = { path = "../srs2dge-text", version = "0.4" }
